### PR TITLE
Websocket and 1.17 stuff.

### PR DESCRIPTION
**Pull request by tk2217**
Makes the item api and tablist stars client use the same websocket lib and fixes/cleans up a few other things.

### CODE REVIEW

**Comment by Owen1212055** [comment]
Assuming this is tested, very good. Removing all those bulk dependencies will help with the massive size of the jar.

Just make sure this works with stuff like Ottelino's online template viewer https://derpystuff.gitlab.io/code/

**Comment by tk2217** [comment]
I tested this with manually connecting over tcp and websocket but ill also test ottelino's tepmplate viewer.

**Comment by tk2217** [comment]
I've confirmed that the web template viewer works fine.

**Comment by Owen1212055** [comment]
Great job!

**Review by Owen1212055 — APPROVED** [review]

**Pull request merged**
