### PR TITLE
Updated menu icons and cleared out un-needed images

### PR DESCRIPTION
**Pull request by 8Blits**

### CODE REVIEW

**Comment by KabanFriends** [comment]
image
How about adding node numbers in the icon like this?

**Comment by AstroSquared** [comment]
i like this

**Comment by 8Blits** [comment]
> image How about adding node numbers in the icon like this?

I can do that!

**Comment by 8Blits** [comment]
@KabanFriends is that more of what you wanted?

**Review by TechStreetDev — APPROVED** [review]
👍🏻

**Comment by AstroSquared** [comment]
hey @BlazeMCworld can you check out this pr

**Review by tk2217 — APPROVED** [review]

**Pull request merged**
