### PR TITLE
Use the GitHub api to check latest version.

### PR DESCRIPTION
**Pull request by Reasonlesss**

### CODE REVIEW

**Comment by Reasonlesss** [comment]
Yes!

**Review by Vatten — APPROVED** [review]
whatever

**Review by tk2217 — APPROVED** [review]
This is going to get very tedious very quickly.

**Comment by Reasonlesss** [comment]
Mostly a temporary thing until we sort something out.

**Review by BlazeMCworld — APPROVED** [review]

**Review by Severnarch — COMMENTED** [review]
cool

**Pull request merged**
