### PR TITLE
Finnish language support

### PR DESCRIPTION
**Pull request by SirObby**
Translated CodeUtilities to Finnish
and thats about it.

### CODE REVIEW

**Review by TechStreetDev — COMMENTED** [review]
Looks cool :D no finish word for "Node"?

**Comment by ryandev2** [comment]
> Looks cool :D no finish word for "Node"?

node is a word used on df everywhere, would be confusing to change

**Comment by SirObby** [comment]
There isnt really another word for node

**Comment by SirObby** [comment]
Also Reasonless told me to push this to github so I did a PR lul

**Comment by SirObby** [comment]
Can someone merge this?

**Comment by TechStreetDev** [comment]
reason will when he gets a chance

**Comment by SirObby** [comment]
Ah Ok

**Comment by TechStreetDev** [comment]
k

**Comment by KabanFriends** [comment]
hi

I'm merge

**Pull request merged**
