### PR TITLE
Various 1.17 bugfixes and tweaks.

### PR DESCRIPTION
**Pull request by tk2217**
This pr makes changes to build.gradle to greatly simplify it and to get the mod running outside of the fabric development environment. This also increases the fabric and yarn versions.

### CODE REVIEW

**Comment by KabanFriends** [comment]
didnt expect a pull request in 1.17 branch lol

**Comment by Tomoli75** [comment]
wait did you literally make 1.17 work

**Comment by tk2217** [comment]
Yes lol. Also, more todos will be fixed very soon (probably today). The main headache was getting shadow to work

**Comment by tk2217** [comment]
for now it looks like everything has been updated to 1.17

**Comment by Vatten** [comment]
why was ctextfield removed?

**Comment by tk2217** [comment]
it was a copy of WTextField and was just duplicating code

**Comment by Vatten** [comment]
No i think it overrided the disabled color to make it red (to display errors)

**Comment by tk2217** [comment]
I'll take a look at it as soon as I can

**Comment by tk2217** [comment]
from what i can see from the previous implementation there wasn't any code for making the disabled color red or similair

**Comment by tk2217** [comment]
AFAIK this is mostly ready to merge unless I made any random mistakes with rendering and stuff.

**Review by Reasonlesss — APPROVED** [review]
Looks gucci merging.

**Comment by Owen1212055** [comment]
Impressive job.

**Pull request merged**
