### PR TITLE
Add ResourcePack support

### PR DESCRIPTION
**Pull request by Severnarch**

### CODE REVIEW

**Review by Reasonlesss — APPROVED** [review]
All good

**Review by Reasonlesss — CHANGES_REQUESTED** [review]
Why was the df logo changed?

**Comment by Severnarch** [comment]
> Why was the df logo changed?

i forgot to undo my localside df.png change, that's why
[edit: changed it back]

**Review by RedVortexDev — APPROVED** [review]
yes i approve

**Review by Reasonlesss — APPROVED** [review]
Looks good

**Review by TechStreetDev — COMMENTED** [review]
All good

**Review by TechStreetDev — APPROVED** [review]

**Review by Vatten — APPROVED** [review]

**Pull request merged**
